// constant about actions

export const REQUEST_API = 'REQUEST_API';
export const REQUEST_API_SUCCESS = 'REQUEST_API_SUCCESS';
export const REQUEST_API_SUCCESS_ALL = 'REQUEST_API_SUCCESS_ALL';
export const REQUEST_API_ERROR = 'REQUEST_API_ERROR';